### PR TITLE
fix android crashpad initialization, fix settings

### PR DESCRIPTION
**Pull request by bobbyg603**
### Description

PR from @munkiki7 for the commit that was accidentally pushed to main.

### Checklist

- [x] Tested manually
- [x] Unit tests pass with no errors or warnings
- [x] Documentation updated (if applicable)
- [x] Reviewed by at least 1 other contributor

### CODE REVIEW

**Comment by bobbyg603** [comment]
@munkiki7 I got around to testing this today and it's likely I did something wrong.  When I run my-unreal-crasher on Android it crashes on load trying to find libcrashpad_handler.so.

```
java.lang.UnsatisfiedLinkError: dlopen failed: library "libcrashpad_handler.so" not found: needed by /data/app/~~z9lPGxY8-w81kPIt4n_iew==/com.BugSplat.MyUnrealCrasher-qK3v7P0RKuUb-8r7HgedHg==/lib/arm64/libUnreal.so in namespace classloader-namespace
```

Additionally, I don't see libcrashpad_handler.so in the intermediate project so my guess is I missed something that copies that file to the intermediate project and/or device. Does this PR include all of the necessary changes for Android or is there something missing?

The device I'm testing on is a HW Pixel 3 Android 12 API 32 (Arm64-v8a ABI?)

**Comment by tustanivsky** [comment]
@bobbyg603 I've managed to run the Android version without any issues and `libcrashpad_handler.so` seem to be in the right place.
image
The problem might be related to Android 12 though. Can you try this out on an older device?

**Comment by tustanivsky** [comment]
@bobbyg603 quick update regarding the `.aar` wrapper - in case with UE this approach doesn't seem to work. I've tried to replace native libraries with a single `.aar` and even though the crashpad initialization method returns `true` the actual crashes don't appear in the BugSplat dashboard. What's more they don't get saved locally as well like in the screenshot from the previous message

**Comment by bobbyg603** [comment]
@tustanivsky i've made some progress here.

The reason we're seeing dump files on device, but not on BugSplat is because BugSplat recently started blocking http traffic. The version of Crashpad we're using was compiled before Crashpad added support for https on Android/Linux. I have successfully built a newer version of Crashpad, but I'm seeing the same behavior as you did, where startHandler returns true, but fails to write a dump file. I think if I can figure out how to get a newer build of crashpad working the `.aar` wrapper would be worth a try.

With regard to the change to load the library from the `lib` directory, the library directory seems to have changed in newer versions of Android, but I can't seem to find any documentation that lists the new location. Can you help me find the new location of the `lib` directory? In the past I've used adb to find libcrashpad_handler.so on device, and I've been able to execute it and verify it's working (it's really an executable disguised as a shared library). 

Any guidance you're able to offer is much appreciated. In the meantime I'll continue investigating.

**Comment by bobbyg603** [comment]
@tustanivsky another update, i realized that you can only get and adb root shell via the emulator. i've switched to another device and have invoked the crashpad handler executable. apparently it is having trouble loading libc++_shared.so despite that library being next to it on the file system. i will continue investigating and will keep you updated when i can figure out next steps.

**Pull request merged**
