### PR TITLE
feat!: move plugin controls to project settings

### PR DESCRIPTION
**Pull request by tustanivsky**
- Fix debug symbols upload
- Update demo scene
- Rework plugin settings panel

### CODE REVIEW

**Comment by bobbyg603** [comment]
Great work! After getting my hands on this PR I think there are some easy things we can do to improve the UX:

- [ ] “Crash Reported Configuration” → “Crash Reporter Configuration”
- [ ] Create new “Desktop” section
    - [ ] Move “Update INI” and “Add Symbol Uploads” Buttons into a “Desktop” section
    - [ ] Move Update Game INI so that it is the first button from the left
- [ ] Replace Client ID and Client Secret with User and Password (no changes to the way SendPdbs is invoked should be required, just replace ClientId and ClientSecret with existing User and Password)
    - [ ] Bobby will create an issue and convert to ClientID and Client Secret when iOS and Android support them
- [ ] Remove the “Enable Automatic Symbols Upload” checkbox in Common (this will be moved to platform specific sections)
- [ ]Create an iOS section
    - [ ]Add checkbox for “Enable iOS Crash Reporting” that is enabled by default
    - [ ]Create a new instance of “Enable automatic symbol uploads” checkbox and have it toggle iOS symbol uploads only
- [ ] Create an Android section
    - [ ]Add checkbox for “Enable Android Crash Reporting” that is disabled and read-only
        - [ ] If we can add a tooltip for a readonly disabled checkbox, have it say “Android Support Coming Soon”
        - [ ] If we can’t add a tooltip for a readonly disabled checkbox, add a snippet of text to the section that says “Android Support Coming Soon”
    - [ ] Create a new instance of “Enable automatic symbol uploads” checkbox and have it toggle iOS symbol uploads only
        - [ ] Disabled and readonly by default, similar to the “Enable Android Crash Reporting” checkbox above

**Comment by bobbyg603** [comment]
We seem to be getting Symbols, but the crash isn't processing with line numbers. Has anything changed since the first prototype you sent? Is there a specific way I need to package/launch the app in order to get line numbers in the symbol information?

Also, I believe we have a limitation where we require Bitcode to be set to "off". Can you please confirm Bitcode is being set to "off"?

**Comment by tustanivsky** [comment]
> We seem to be getting Symbols for function names, but the crash isn't processing with line numbers. Has anything changed since the first prototype you sent? Is there a specific way I need to package/launch the app in order to get line numbers in the symbol information?
> 
> Also, I believe we have a limitation where line numbers require Bitcode to be set to "off". Can you please confirm Bitcode is being set to "off"?

I believe Bitcode is disabled by default in Unreal, however it's possible to enable it for Shipping builds in project settings if one needs that.
Usually, I just hit the `Launch` button to test the demo on iOS device and it looks like the line numbers are included in a report as expected.

**Review by bobbyg603 — APPROVED** [review]
Excellent work here!

**Pull request merged**
