### PR TITLE
fix: symbol upload fails for large numbers of files

### PR DESCRIPTION
**Pull request by bobbyg603**
### Description

Updates symbol-upload to v9.1.1 with this fix https://github.com/BugSplat-Git/symbol-upload/issues/119

### Checklist

- [x] Tested manually
- [x] Unit tests pass with no errors or warnings
- [x] Documentation updated (if applicable)
- [ ] Reviewed by at least 1 other contributor

### CODE REVIEW

**Comment by bobbyg603** [comment]
@daveplunkett is on the road and will comment when he is back at a keyboard

**Review by daveplunkett — COMMENTED** [review]
Nice

**Comment by fuzzybotcg** [comment]
We're getting this warning from symbol-upload that's throwing off our automated build systems. Symbols seem to be uploading fine(?) Anyway to silence the warning?

`(node:1660) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time (Use `symbol-upload-windows --trace-warnings ...` to show where the warning was created)
`

**Comment by bobbyg603** [comment]
> We're getting this warning from symbol-upload that's throwing off our automated build systems. Symbols seem to be uploading fine(?) Anyway to silence the warning?
> 
> `(node:1660) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time (Use `symbol-upload-windows --trace-warnings ...`to show where the warning was created)`

Hi @fuzzybotcg the issue you mentioned is fixed in the v1.3.4 release, available for download [here](https://github.com/BugSplat-Git/bugsplat-unreal/releases/tag/v1.3.4). It will also be available via the Unreal Marketplace soon.

**Pull request merged**
